language: python
sudo: required
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements/production.txt
# command to run tests
script:
  - cp etc/key.txt.example etc/key.txt
  - cp etc/andromeda.ini.example etc/andromeda.ini
  - python manage.py migrate
  - python manage.py test
